project:
  type: website
  output-dir: docs

website:
  title: "Nish Etige"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: abt.qmd
        text: About Me
      - href: experience.qmd
        text: Research
      - href: pubs.qmd
        text: Publications
      - href: CV.qmd
        text: CV
      - href: resume.qmd
        text: Resume
      - href: highlights.qmd
        text: Past Highlights
        
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    self-contained: true
    code-background: true

editor: visual

